-- 1. Create Profiles Table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'admin',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Program Stats Table (For Charts)
CREATE TABLE program_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month_name TEXT NOT NULL,
  compliance_score INTEGER NOT NULL,
  nutritious_score INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create Operational Workflow Table
CREATE TABLE operational_workflow (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  step_name TEXT NOT NULL, -- 'Pemasakan', 'QC Lab', etc.
  status TEXT NOT NULL,    -- 'Aktif', 'Berjalan', 'Pending'
  unit_count TEXT NOT NULL,
  is_active BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create Food Safety Alerts
CREATE TABLE food_safety_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location TEXT NOT NULL,
  issue_description TEXT NOT NULL,
  severity TEXT DEFAULT 'warning',
  resolved BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Seeding Data
INSERT INTO program_stats (month_name, compliance_score, nutritious_score) VALUES
('Jan', 85, 90), ('Feb', 88, 92), ('Mar', 92, 89), ('Apr', 90, 94);

INSERT INTO operational_workflow (step_name, status, unit_count, is_active) VALUES
('Pemasakan', 'Aktif', '512 Unit', true),
('QC Lab', 'Berjalan', '714 Unit', true),
('Packaging', 'Pending', '128 Unit', false),
('Distribusi', 'Siaga', '1.2k Armada', false);

INSERT INTO food_safety_alerts (location, issue_description, severity) VALUES
('SPPG Kediri #11', 'Suhu pendingin bahan baku di atas 10°C.', 'danger'),
('SPPG Surabaya #04', 'Keterlambatan pasokan sayur segar > 1 jam.', 'warning');